### ISSUE TITLE
Approaches

### ISSUE THREAD

**Issue by ocefpaf** [cliu3/gradient#2]
Way to approach the problem:
1. **Generic solution**: would depend on the calculation of a orthogonal line to a given bathymetric contour.
2. **Domain/grid specific solution**: Adjust "lines" that would represent the bathymetric/coast contour and divide in areas for each line.  Then compute the line `angle` and the `along`/`cross-gradient` for each area using those angles.

@cliu3 Ideas?

TODO:
- [ ] Grid file
- [ ] Bathymetry
- [ ] _u_, _v_ data

**Comment by cliu3** [comment]
I would prefer the second.

**Comment by ocefpaf** [comment]
It is probably the easiest way to solve a particular problem, but for that we need the actual grid and bathymetry to define the aforementioned lines.  Is Kelly on github?  @cliu3  Can you ping her to this issue?

PS: We can keep the first approach as a long term goal though :wink:
